Help
**Note: under Linux, installation of .xml files was optional before this MR (using a dedicated configure option). This option has been removed as .xml files are now mandatory for the `help()` function.**

#17394

Co-authored-by: Cédric DELAMARRE <cedric.delamarre@3ds.com>
Co-authored-by: Clément DAVID <clement.david@3ds.com>
Co-authored-by: Vincent COUVERT <vincent.couvert@3ds.com>
Co-authored-by: Stéphane MOTTELET <stephane.mottelet@utc.fr>
Co-authored-by: Adeline CARNIS <adeline.carnis@3ds.com>
Co-authored-by: Bruno JOFRET <bruno.jofret@3ds.com>
Closes #2252, #15368, #10180, #17526, #17525, #3831, #17511, #17508, #17512, #17504, #17513, #15773, #15101, #17501, #16501, #17496, #17502, #17052, #16744, and #16739
See https://gitlab.com/scilab/scilab/-/merge_requests/1590

diff --git a/scilab/Makefile.in b/scilab/Makefile.in
--- a/scilab/Makefile.in
+++ b/scilab/Makefile.in
@@ -728,6 +728,9 @@ LIBM = @LIBM@
 LIBOBJS = @LIBOBJS@
 LIBS = @LIBS@
 LIBTOOL = @LIBTOOL@
+LIBXSLT_CFLAGS = @LIBXSLT_CFLAGS@
+LIBXSLT_LDFLAGS = @LIBXSLT_LDFLAGS@
+LIBXSLT_LIBS = @LIBXSLT_LIBS@
 LIPO = @LIPO@
 LN_S = @LN_S@
 LOGGING_LEVEL = @LOGGING_LEVEL@
@@ -1030,7 +1033,7 @@ DOCIMAGES = scilab_images.jar
 
 # Path to built files
 PATHTODOCFILES = modules/helptools/jar/
-PATHTOHELPFILES = modules/helptools/inline/
+PATHTOHELPFILES = modules/core/inline/
 
 # Path to scirenderer jar
 PATHTOSCIRENDERER = modules/scirenderer/jar/
@@ -2309,39 +2312,38 @@ javadoc-all:
 	-sourcepath $$LISTMODULES \
 	$$LISTPKG
 
-doc-inline-fr_FR:
-	@$(MAKE) $(AM_MAKEFLAGS) doc-inline ALL_LINGUAS_DOC=fr_FR
+help-fr_FR:
+	@$(MAKE) $(AM_MAKEFLAGS) help ALL_LINGUAS_DOC=fr_FR
 
-doc-inline-en_US:
-	@$(MAKE) $(AM_MAKEFLAGS) doc-inline ALL_LINGUAS_DOC=en_US
+help-en_US:
+	@$(MAKE) $(AM_MAKEFLAGS) help ALL_LINGUAS_DOC=en_US
 
-doc-inline-pt_BR:
-	@$(MAKE) $(AM_MAKEFLAGS) doc-inline ALL_LINGUAS_DOC=pt_BR
+help-pt_BR:
+	@$(MAKE) $(AM_MAKEFLAGS) help ALL_LINGUAS_DOC=pt_BR
 
-doc-inline-ru_RU:
-	@$(MAKE) $(AM_MAKEFLAGS) doc-inline ALL_LINGUAS_DOC=ru_RU
+help-ru_RU:
+	@$(MAKE) $(AM_MAKEFLAGS) help ALL_LINGUAS_DOC=ru_RU
 
-doc-inline-ja_JP:
-	@$(MAKE) $(AM_MAKEFLAGS) doc-inline ALL_LINGUAS_DOC=ja_JP
+help-ja_JP:
+	@$(MAKE) $(AM_MAKEFLAGS) help ALL_LINGUAS_DOC=ja_JP
 
-doc-inline: $(top_builddir)/scilab-bin $(top_builddir)/bin/scilab-cli
-@BUILD_HELP_TRUE@	@if test -x $(top_builddir)/scilab-bin; then \
-@BUILD_HELP_TRUE@		cd $(top_builddir);\
-@BUILD_HELP_TRUE@		for l in $(ALL_LINGUAS_DOC); do \
-@BUILD_HELP_TRUE@			echo "-- Building help ($$l) --"; \
-@BUILD_HELP_TRUE@			COMMAND="try xmltoinline([],[],'$$l');catch disp(lasterror()); exit(-1);end;exit(0);"; \
-@BUILD_HELP_TRUE@			if test "$(MACOSX)" = "1"; then \
-@BUILD_HELP_TRUE@				echo "LANG=$$l.UTF-8 HOME=/tmp $(top_builddir)/bin/scilab-cli -noatomsautoload -nb -l $$l -nouserstartup -e \"$$COMMAND\"";\
-@BUILD_HELP_TRUE@				LANG=$$l.UTF-8 HOME=/tmp $(top_builddir)/bin/scilab-cli -noatomsautoload -nb -l $$l -nouserstartup -e "$$COMMAND" || exit 1;\
-@BUILD_HELP_TRUE@			else \
-@BUILD_HELP_TRUE@				echo "LANG=$$l.UTF-8 LC_ALL=C HOME=/tmp $(top_builddir)/bin/scilab-cli -noatomsautoload -nb -l $$l -nouserstartup -e \"$$COMMAND\"";\
-@BUILD_HELP_TRUE@				LANG=$$l.UTF-8 LC_ALL=C HOME=/tmp $(top_builddir)/bin/scilab-cli -noatomsautoload -nb -l $$l -nouserstartup -e "$$COMMAND" || exit 1;\
-@BUILD_HELP_TRUE@			fi; \
-@BUILD_HELP_TRUE@		done; \
-@BUILD_HELP_TRUE@	else \
-@BUILD_HELP_TRUE@		echo "Cannot find scilab-cli binary"; \
-@BUILD_HELP_TRUE@	fi
-@BUILD_HELP_FALSE@	@echo "Cannot buid help. Add --enable-build-help to the ./configure if you want to build it."
+help: $(top_builddir)/scilab-bin $(top_builddir)/bin/scilab-cli
+	@if test -x $(top_builddir)/scilab-bin; then \
+		cd $(top_builddir);\
+		for l in $(ALL_LINGUAS_DOC); do \
+			echo "-- Building help ($$l) --"; \
+			COMMAND="try generate_inline_links('$$l');catch disp(lasterror()); exit(-1);end;exit(0);"; \
+			if test "$(MACOSX)" = "1"; then \
+				echo "LANG=$$l.UTF-8 HOME=/tmp $(top_builddir)/bin/scilab-cli -noatomsautoload -nb -l $$l -nouserstartup -e \"$$COMMAND\"";\
+				LANG=$$l.UTF-8 HOME=/tmp $(top_builddir)/bin/scilab-cli -noatomsautoload -nb -l $$l -nouserstartup -e "$$COMMAND" || exit 1;\
+			else \
+				echo "LANG=$$l.UTF-8 LC_ALL=C HOME=/tmp $(top_builddir)/bin/scilab-cli -noatomsautoload -nb -l $$l -nouserstartup -e \"$$COMMAND\"";\
+				LANG=$$l.UTF-8 LC_ALL=C HOME=/tmp $(top_builddir)/bin/scilab-cli -noatomsautoload -nb -l $$l -nouserstartup -e "$$COMMAND" || exit 1;\
+			fi; \
+		done; \
+	else \
+		echo "Cannot find scilab-cli binary"; \
+	fi
 
 doc-fr_FR:
 	@$(MAKE) $(AM_MAKEFLAGS) doc ALL_LINGUAS_DOC=fr_FR
@@ -2592,17 +2594,6 @@ install-data-local:
 @BUILD_HELP_TRUE@	    	$(INSTALL_DATA) "$$file" $(DESTDIR)$(pkgdatadir)/$(PATHTODOCFILES) ; \
 @BUILD_HELP_TRUE@		done; \
 @BUILD_HELP_TRUE@	fi
-# Inline help
-@BUILD_HELP_TRUE@	@$(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES); \
-@BUILD_HELP_TRUE@	echo $(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES); \
-@BUILD_HELP_TRUE@	for lang in $(ALL_LINGUAS); do \
-@BUILD_HELP_TRUE@		if test -d $(top_builddir)/$(PATHTOHELPFILES)/$$lang/; then \
-@BUILD_HELP_TRUE@			echo $(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES)/$$lang; \
-@BUILD_HELP_TRUE@			$(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES)/$$lang; \
-@BUILD_HELP_TRUE@			echo $(INSTALL_DATA) $(top_builddir)/$(PATHTOHELPFILES)/$$lang/*.* $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES)/$$lang/; \
-@BUILD_HELP_TRUE@			$(INSTALL_DATA) $(top_builddir)/$(PATHTOHELPFILES)/$$lang/*.* $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES)/$$lang/; \
-@BUILD_HELP_TRUE@		fi \
-@BUILD_HELP_TRUE@	done
 @BUILD_HELP_TRUE@	@if test -d $(PATHTOJAVASCIDOC); then \
 @BUILD_HELP_TRUE@	$(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/$(PATHTOJAVASCIDOC); \
 @BUILD_HELP_TRUE@	echo $(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/$(PATHTOJAVASCIDOC); \
@@ -2615,6 +2606,17 @@ install-data-local:
 @BUILD_HELP_TRUE@			done; \
 @BUILD_HELP_TRUE@	done; \
 @BUILD_HELP_TRUE@	fi
+# Inline help index (always built & available)
+	@$(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES); \
+	echo $(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES); \
+	for lang in $(ALL_LINGUAS); do \
+		if test -d $(top_builddir)/$(PATHTOHELPFILES)/$$lang/; then \
+			echo $(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES)/$$lang; \
+			$(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES)/$$lang; \
+			echo $(INSTALL_DATA) $(top_builddir)/$(PATHTOHELPFILES)/$$lang/*.* $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES)/$$lang/; \
+			$(INSTALL_DATA) $(top_builddir)/$(PATHTOHELPFILES)/$$lang/*.* $(DESTDIR)$(pkgdatadir)/$(PATHTOHELPFILES)/$$lang/; \
+		fi \
+	done
 # Also install scirenderer.jar
 @EXTERNAL_SCIRENDERER_FALSE@@GUI_TRUE@	$(mkinstalldirs) $(DESTDIR)$(pkgdatadir)/$(PATHTOSCIRENDERER)
 @EXTERNAL_SCIRENDERER_FALSE@@GUI_TRUE@	$(INSTALL_DATA) $(top_builddir)/$(PATHTOSCIRENDERER)/$(SCIRENDERERJAR) $(DESTDIR)$(pkgdatadir)/$(PATHTOSCIRENDERER)/
